import pyautogui
import time

pyautogui.press('winleft')
time.sleep(1)
pyautogui.write('chrome')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(423, 62, 0.5)
time.sleep(1)
pyautogui.click()
time.sleep(1)
pyautogui.write('https://www.youtube.com.br')
time.sleep(1)
pyautogui.press('enter')
time.sleep(3)
pyautogui.moveTo(1068, 148, 0.5)
pyautogui.click()
time.sleep(1)
pyautogui.write('one bit code')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.moveTo(1956, 603, 0.5)
time.sleep(1)
pyautogui.click()
time.sleep(1)
pyautogui.alert(title = 'Agradecimento', text = 'Obrigado por se inscrever no cala', button = 'OK')